-- show all indexes for all tables in the current database
SELECT DISTINCT
    TABLE_NAME,
    INDEX_NAME
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = database()
ORDER BY TABLE_NAME, INDEX_NAME;
